name: dgbed
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - blas=1.0=mkl
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2022.2.1=h06a4308_0
  - certifi=2021.10.8=py38h06a4308_2
  - cffi=1.15.0=py38hd667e15_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=36.0.0=py38h9ce1e76_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - cudnn=7.6.5.32=h01f27c4_1
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.10.4=h7ca028e_0
  - future=0.18.2=py38h578d9bd_4
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - importlib-metadata=4.11.2=py38h578d9bd_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9d=h7f8727e_0
  - lame=3.100=h7b6447c_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libblas=3.9.0=12_linux64_mkl
  - libcblas=3.9.0=12_linux64_mkl
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgomp=9.3.0=h5101ec6_17
  - libiconv=1.15=h63c8f33_5
  - libidn2=2.3.2=h7f8727e_0
  - liblapack=3.9.0=12_linux64_mkl
  - libpng=1.6.37=h21135ba_2
  - libprotobuf=3.19.1=h4ff587b_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.0.10=hc3755c2_1005
  - libunistring=0.9.10=h27cfd23_0
  - libuv=1.40.0=h7b6447c_0
  - lz4-c=1.9.2=he1b5a44_3
  - magma=2.5.4=h5da55e3_2
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - nccl=2.11.4.1=h1a5f58c_2
  - ncurses=6.2=he6710b0_1
  - nettle=3.7.3=hbbd107a_1
  - ninja=1.10.2=py38hd09550d_3
  - numpy-base=1.21.2=py38h79a1101_0
  - olefile=0.46=pyh9f0ad1d_1
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1n=h7f8727e_0
  - pip=21.2.2=py38h06a4308_0
  - prettytable=3.2.0=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.11=h12debd9_0_cpython
  - python_abi=3.8=2_cp38
  - pytorch-mutex=1.0=cuda
  - readline=8.1=h27cfd23_0
  - setuptools=52.0.0=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sleef=3.5.1=h516909a_0
  - sqlite=3.36.0=hc218d9a_0
  - timm=0.4.12=pyhd8ed1ab_0
  - tk=8.6.10=hbc83047_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zipp=3.7.0=pyhd8ed1ab_1
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - cycler==0.11.0
    - einops==0.4.1
    - filelock==3.0.12
    - fonttools==4.30.0
    - ftfy==6.1.1
    - gdown==3.13.0
    - idna==3.2
    - imageio==2.18.0
    - joblib==1.0.1
    - kiwisolver==1.4.0
    - littleutils==0.2.2
    - matplotlib==3.5.1
    - munch==2.5.0
    - networkx==2.8
    - numpy==1.21.1
    - ogb==1.3.1
    - opencv-python==4.5.5.64
    - outdated==0.2.1
    - packaging==21.3
    - pandas==1.3.1
    - parameterized==0.8.1
    - pillow==9.1.0
    - pydeprecate==0.3.2
    - pyparsing==3.0.7
    - python-dateutil==2.8.2
    - pytz==2021.1
    - pywavelets==1.3.0
    - regex==2022.7.25
    - requests==2.26.0
    - scikit-image==0.19.2
    - scikit-learn==1.0.2
    - scipy==1.7.1
    - seaborn==0.11.2
    - threadpoolctl==2.2.0
    - tifffile==2022.4.22
    - torch==1.9.0+cu111
    - torchaudio==0.9.0
    - torchmetrics==0.8.0
    - torchvision==0.10.0
    - tqdm==4.62.0
    - typing-extensions==3.10.0.0
    - urllib3==1.26.6
    - vit-pytorch==0.27.0
    - wilds==1.2.2
